/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MyTocRouteImport } from './routes/my-toc'
import { Route as MySupportAgent2RouteImport } from './routes/my-support-agent-2'
import { Route as MyLokrRouteImport } from './routes/my-lokr'
import { Route as MySecretAgentRouteImport } from './routes/my-secret-agent'
import { Route as MnybusinessRouteImport } from './routes/mnybusiness'
import { Route as MnyRouteImport } from './routes/mny'
import { Route as LnklokrRouteImport } from './routes/lnklokr'
import { Route as GoShopRouteImport } from './routes/go-shop'
import { Route as GoNewsAppRouteImport } from './routes/go-news-app'
import { Route as GiaRouteImport } from './routes/gia'
import { Route as GetSupportRouteImport } from './routes/get-support'
import { Route as FridayCanvasRouteImport } from './routes/friday-canvas'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as AppsRouteImport } from './routes/apps'
import { Route as ChkchkRouteImport } from './routes/chkchk'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTocRoute = MyTocRouteImport.update({
  id: '/my-toc',
  path: '/my-toc',
  getParentRoute: () => rootRouteImport,
} as any)
const MySupportAgent2Route = MySupportAgent2RouteImport.update({
  id: '/my-support-agent-2',
  path: '/my-support-agent-2',
  getParentRoute: () => rootRouteImport,
} as any)
const MyLokrRoute = MyLokrRouteImport.update({
  id: '/my-lokr',
  path: '/my-lokr',
  getParentRoute: () => rootRouteImport,
} as any)
const MySecretAgentRoute = MySecretAgentRouteImport.update({
  id: '/my-secret-agent',
  path: '/my-secret-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const MnybusinessRoute = MnybusinessRouteImport.update({
  id: '/mnybusiness',
  path: '/mnybusiness',
  getParentRoute: () => rootRouteImport,
} as any)
const MnyRoute = MnyRouteImport.update({
  id: '/mny',
  path: '/mny',
  getParentRoute: () => rootRouteImport,
} as any)
const LnklokrRoute = LnklokrRouteImport.update({
  id: '/lnklokr',
  path: '/lnklokr',
  getParentRoute: () => rootRouteImport,
} as any)
const GoShopRoute = GoShopRouteImport.update({
  id: '/go-shop',
  path: '/go-shop',
  getParentRoute: () => rootRouteImport,
} as any)
const GoNewsAppRoute = GoNewsAppRouteImport.update({
  id: '/go-news-app',
  path: '/go-news-app',
  getParentRoute: () => rootRouteImport,
} as any)
const GiaRoute = GiaRouteImport.update({
  id: '/gia',
  path: '/gia',
  getParentRoute: () => rootRouteImport,
} as any)
const GetSupportRoute = GetSupportRouteImport.update({
  id: '/get-support',
  path: '/get-support',
  getParentRoute: () => rootRouteImport,
} as any)
const FridayCanvasRoute = FridayCanvasRouteImport.update({
  id: '/friday-canvas',
  path: '/friday-canvas',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRoute = AppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const ChkchkRoute = ChkchkRouteImport.update({
  id: '/chkchk',
  path: '/chkchk',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apps': typeof AppsRoute
  '/chkchk': typeof ChkchkRoute
  '/desk': typeof DeskRoute
  '/friday-canvas': typeof FridayCanvasRoute
  '/get-support': typeof GetSupportRoute
  '/gia': typeof GiaRoute
  '/go-news-app': typeof GoNewsAppRoute
  '/go-shop': typeof GoShopRoute
  '/lnklokr': typeof LnklokrRoute
  '/mny': typeof MnyRoute
  '/mnybusiness': typeof MnybusinessRoute
  '/my-secret-agent': typeof MySecretAgentRoute
  '/my-lokr': typeof MyLokrRoute
  '/my-support-agent-2': typeof MySupportAgent2Route
  '/my-toc': typeof MyTocRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apps': typeof AppsRoute
  '/chkchk': typeof ChkchkRoute
  '/desk': typeof DeskRoute
  '/friday-canvas': typeof FridayCanvasRoute
  '/get-support': typeof GetSupportRoute
  '/gia': typeof GiaRoute
  '/go-news-app': typeof GoNewsAppRoute
  '/go-shop': typeof GoShopRoute
  '/lnklokr': typeof LnklokrRoute
  '/mny': typeof MnyRoute
  '/mnybusiness': typeof MnybusinessRoute
  '/my-lokr': typeof MyLokrRoute
  '/my-secret-agent': typeof MySecretAgentRoute
  '/my-support-agent-2': typeof MySupportAgent2Route
  '/my-toc': typeof MyTocRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apps': typeof AppsRoute
  '/chkchk': typeof ChkchkRoute
  '/desk': typeof DeskRoute
  '/friday-canvas': typeof FridayCanvasRoute
  '/get-support': typeof GetSupportRoute
  '/gia': typeof GiaRoute
  '/go-news-app': typeof GoNewsAppRoute
  '/go-shop': typeof GoShopRoute
  '/lnklokr': typeof LnklokrRoute
  '/mny': typeof MnyRoute
  '/mnybusiness': typeof MnybusinessRoute
  '/my-lokr': typeof MyLokrRoute
  '/my-secret-agent': typeof MySecretAgentRoute
  '/my-support-agent-2': typeof MySupportAgent2Route
  '/my-toc': typeof MyTocRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apps'
    | '/chkchk'
    | '/desk'
    | '/friday-canvas'
    | '/get-support'
    | '/gia'
    | '/go-news-app'
    | '/go-shop'
    | '/lnklokr'
    | '/mny'
    | '/mnybusiness'
    | '/my-lokr'
    | '/my-secret-agent'
    | '/my-support-agent-2'
    | '/my-toc'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apps'
    | '/chkchk'
    | '/desk'
    | '/friday-canvas'
    | '/get-support'
    | '/gia'
    | '/go-news-app'
    | '/go-shop'
    | '/lnklokr'
    | '/mny'
    | '/mnybusiness'
    | '/my-lokr'
    | '/my-secret-agent'
    | '/my-support-agent-2'
    | '/my-toc'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/apps'
    | '/chkchk'
    | '/desk'
    | '/friday-canvas'
    | '/get-support'
    | '/gia'
    | '/go-news-app'
    | '/go-shop'
    | '/lnklokr'
    | '/mny'
    | '/mnybusiness'
    | '/my-lokr'
    | '/my-secret-agent'
    | '/my-support-agent-2'
    | '/my-toc'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppsRoute: typeof AppsRoute
  ChkchkRoute: typeof ChkchkRoute
  DeskRoute: typeof DeskRoute
  FridayCanvasRoute: typeof FridayCanvasRoute
  GetSupportRoute: typeof GetSupportRoute
  GiaRoute: typeof GiaRoute
  GoNewsAppRoute: typeof GoNewsAppRoute
  GoShopRoute: typeof GoShopRoute
  LnklokrRoute: typeof LnklokrRoute
  MnyRoute: typeof MnyRoute
  MnybusinessRoute: typeof MnybusinessRoute
  MyLokrRoute: typeof MyLokrRoute
  MySecretAgentRoute: typeof MySecretAgentRoute
  MySupportAgent2Route: typeof MySupportAgent2Route
  MyTocRoute: typeof MyTocRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-toc': {
      id: '/my-toc'
      path: '/my-toc'
      fullPath: '/my-toc'
      preLoaderRoute: typeof MyTocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-support-agent-2': {
      id: '/my-support-agent-2'
      path: '/my-support-agent-2'
      fullPath: '/my-support-agent-2'
      preLoaderRoute: typeof MySupportAgent2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-lokr': {
      id: '/my-lokr'
      path: '/my-lokr'
      fullPath: '/my-lokr'
      preLoaderRoute: typeof MyLokrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-secret-agent': {
      id: '/my-secret-agent'
      path: '/my-secret-agent'
      fullPath: '/my-secret-agent'
      preLoaderRoute: typeof MySecretAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mnybusiness': {
      id: '/mnybusiness'
      path: '/mnybusiness'
      fullPath: '/mnybusiness'
      preLoaderRoute: typeof MnybusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mny': {
      id: '/mny'
      path: '/mny'
      fullPath: '/mny'
      preLoaderRoute: typeof MnyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lnklokr': {
      id: '/lnklokr'
      path: '/lnklokr'
      fullPath: '/lnklokr'
      preLoaderRoute: typeof LnklokrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go-shop': {
      id: '/go-shop'
      path: '/go-shop'
      fullPath: '/go-shop'
      preLoaderRoute: typeof GoShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go-news-app': {
      id: '/go-news-app'
      path: '/go-news-app'
      fullPath: '/go-news-app'
      preLoaderRoute: typeof GoNewsAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gia': {
      id: '/gia'
      path: '/gia'
      fullPath: '/gia'
      preLoaderRoute: typeof GiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-support': {
      id: '/get-support'
      path: '/get-support'
      fullPath: '/get-support'
      preLoaderRoute: typeof GetSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friday-canvas': {
      id: '/friday-canvas'
      path: '/friday-canvas'
      fullPath: '/friday-canvas'
      preLoaderRoute: typeof FridayCanvasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chkchk': {
      id: '/chkchk'
      path: '/chkchk'
      fullPath: '/chkchk'
      preLoaderRoute: typeof ChkchkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppsRoute: AppsRoute,
  ChkchkRoute: ChkchkRoute,
  DeskRoute: DeskRoute,
  FridayCanvasRoute: FridayCanvasRoute,
  GetSupportRoute: GetSupportRoute,
  GiaRoute: GiaRoute,
  GoNewsAppRoute: GoNewsAppRoute,
  GoShopRoute: GoShopRoute,
  LnklokrRoute: LnklokrRoute,
  MnyRoute: MnyRoute,
  MnybusinessRoute: MnybusinessRoute,
  MyLokrRoute: MyLokrRoute,
  MySecretAgentRoute: MySecretAgentRoute,
  MySupportAgent2Route: MySupportAgent2Route,
  MyTocRoute: MyTocRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
